#!/bin/bash
# This script should go to /usr/local/bin

script=`readlink -f -- "$1"`
case "$script" in
~/dotfiles/vim/bundle/vim-sparkup/ftplugin/html/*)
    exec python2 "$@"
    ;;
esac

exec python3 "$@"
